version: '3.1'
services:
  api:
    image: node:15.7.0
    entrypoint: ["/bin/sh","-c", ]
    volumes:
       - ./api/:/var/www/html
    working_dir: /var/www/html
    command:
        - |
            npm install
            npm start
    environment:
        - CHOKIDAR_USEPOLLING=true
    ports:
        - 3000:3000
    healthcheck:
      test: ["CMD", "netstat -ltn | grep -c 3000"]
      interval: 2s
      timeout: 2s
      retries: 15

  server:
    image: node:15.7.0
    entrypoint: ["/bin/sh","-c", ]
    volumes:
        - ./server/:/var/www/html
    working_dir: /var/www/html
    depends_on:
        - api
    command:
          - |
            npm install
            ./wait-for-it.sh api:3000
            npm run server
    ports:
        - 8080:8080
